import type { Knex } from 'knex';

/**
 * Baseline migration — v0.2.1
 *
 * Represents the complete schema as of the first DigitalOcean production
 * deployment. All statements are idempotent (IF NOT EXISTS / hasColumn checks)
 * so this is safe to run against both a fresh database and an existing one.
 *
 * DO NOT edit this file. Create a new numbered migration for any future changes.
 */

// ─── Helpers ──────────────────────────────────────────────────────────────────

/** Adds a column only if it doesn't already exist. */
async function addCol(
  knex: Knex,
  table: string,
  column: string,
  def: (t: Knex.AlterTableBuilder) => void,
): Promise<void> {
  if (!(await knex.schema.hasColumn(table, column))) {
    await knex.schema.alterTable(table, def);
  }
}

// ─── Up ───────────────────────────────────────────────────────────────────────

export async function up(knex: Knex): Promise<void> {
  await knex.raw('SET FOREIGN_KEY_CHECKS = 0');

  // ── Core tables (init.sql) ─────────────────────────────────────────────────

  await knex.raw(`
    CREATE TABLE IF NOT EXISTS users (
      id VARCHAR(36) PRIMARY KEY,
      first_name VARCHAR(100) NOT NULL,
      last_name VARCHAR(100) NOT NULL,
      email VARCHAR(255) NOT NULL UNIQUE,
      password_hash VARCHAR(255) NOT NULL,
      role ENUM('SUPER_ADMIN','COMPANY_ADMIN','AGENT','CUSTOMER') NOT NULL,
      company_id VARCHAR(36),
      service_type ENUM('HOTEL','TAXI','EXPERIENCE','CAR','FOOD'),
      is_active BOOLEAN DEFAULT TRUE,
      created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
      updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
      INDEX idx_email (email), INDEX idx_role (role), INDEX idx_company_id (company_id)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
  `);

  await knex.raw(`
    CREATE TABLE IF NOT EXISTS companies (
      id VARCHAR(36) PRIMARY KEY,
      name VARCHAR(255) NOT NULL,
      service_type ENUM('HOTEL','TAXI','EXPERIENCE','CAR','FOOD') NOT NULL,
      description TEXT, logo VARCHAR(500), website VARCHAR(255),
      email VARCHAR(255) NOT NULL, phone VARCHAR(20),
      address VARCHAR(255), city VARCHAR(100), country VARCHAR(100),
      is_verified BOOLEAN DEFAULT FALSE,
      is_active BOOLEAN DEFAULT TRUE,
      created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
      updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
      INDEX idx_service_type (service_type), INDEX idx_is_active (is_active)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
  `);

  await knex.raw(`
    CREATE TABLE IF NOT EXISTS agents (
      id VARCHAR(36) PRIMARY KEY,
      user_id VARCHAR(36) NOT NULL,
      company_id VARCHAR(36) NOT NULL,
      service_type ENUM('HOTEL','TAXI','EXPERIENCE','CAR','FOOD') NOT NULL,
      name VARCHAR(255) NOT NULL, email VARCHAR(255) NOT NULL, phone VARCHAR(20),
      status ENUM('PENDING','APPROVED','ACTIVE','SUSPENDED','INACTIVE') DEFAULT 'PENDING',
      commission_rate DECIMAL(5,2) DEFAULT 0,
      total_bookings INT DEFAULT 0, total_revenue DECIMAL(12,2) DEFAULT 0,
      average_rating DECIMAL(3,2) DEFAULT 0, total_reviews INT DEFAULT 0,
      created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
      updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
      FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
      FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE,
      INDEX idx_company_id (company_id), INDEX idx_status (status), INDEX idx_service_type (service_type)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
  `);

  await knex.raw(`
    CREATE TABLE IF NOT EXISTS company_admins (
      id VARCHAR(36) PRIMARY KEY,
      user_id VARCHAR(36) NOT NULL, company_id VARCHAR(36) NOT NULL,
      admin_role ENUM('OWNER','MANAGER','SUPPORT') NOT NULL,
      name VARCHAR(255) NOT NULL, email VARCHAR(255) NOT NULL, phone VARCHAR(20),
      is_active BOOLEAN DEFAULT TRUE,
      created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
      updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
      FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
      FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE,
      INDEX idx_company_id (company_id), INDEX idx_admin_role (admin_role)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
  `);

  await knex.raw(`
    CREATE TABLE IF NOT EXISTS hotels (
      id VARCHAR(36) PRIMARY KEY,
      company_id VARCHAR(36) NOT NULL, agent_id VARCHAR(36) NOT NULL,
      name VARCHAR(255) NOT NULL, description TEXT,
      status ENUM('DRAFT','ACTIVE','INACTIVE','SUSPENDED') DEFAULT 'DRAFT',
      address VARCHAR(255) NOT NULL, city VARCHAR(100) NOT NULL,
      state VARCHAR(100), country VARCHAR(100) NOT NULL, zip_code VARCHAR(20),
      latitude DECIMAL(10,8), longitude DECIMAL(11,8),
      star_rating INT DEFAULT 0, total_rooms INT DEFAULT 0,
      check_in_time VARCHAR(5) DEFAULT '14:00', check_out_time VARCHAR(5) DEFAULT '11:00',
      cancellation_policy TEXT, custom_policies JSON DEFAULT NULL,
      average_rating DECIMAL(3,2) DEFAULT 0, total_reviews INT DEFAULT 0,
      created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
      updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
      FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE,
      FOREIGN KEY (agent_id) REFERENCES agents(id) ON DELETE CASCADE,
      INDEX idx_company_id (company_id), INDEX idx_agent_id (agent_id),
      INDEX idx_status (status), INDEX idx_city (city), INDEX idx_country (country)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
  `);

  await knex.raw(`
    CREATE TABLE IF NOT EXISTS hotel_amenities (
      id INT AUTO_INCREMENT PRIMARY KEY,
      hotel_id VARCHAR(36) NOT NULL, amenity_name VARCHAR(100) NOT NULL,
      is_available BOOLEAN DEFAULT TRUE,
      FOREIGN KEY (hotel_id) REFERENCES hotels(id) ON DELETE CASCADE,
      INDEX idx_hotel_id (hotel_id),
      UNIQUE KEY unique_hotel_amenity (hotel_id, amenity_name)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
  `);

  await knex.raw(`
    CREATE TABLE IF NOT EXISTS hotel_images (
      id INT AUTO_INCREMENT PRIMARY KEY,
      hotel_id VARCHAR(36) NOT NULL, image_url VARCHAR(500) NOT NULL,
      display_order INT DEFAULT 0,
      created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
      FOREIGN KEY (hotel_id) REFERENCES hotels(id) ON DELETE CASCADE,
      INDEX idx_hotel_id (hotel_id)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
  `);

  await knex.raw(`
    CREATE TABLE IF NOT EXISTS room_types (
      id VARCHAR(36) PRIMARY KEY,
      hotel_id VARCHAR(36) NOT NULL,
      name VARCHAR(255) NOT NULL, description TEXT,
      capacity INT NOT NULL, total_rooms INT NOT NULL, available_rooms INT NOT NULL,
      base_price DECIMAL(10,2) NOT NULL, currency VARCHAR(3) DEFAULT 'USD',
      status ENUM('ACTIVE','INACTIVE') DEFAULT 'ACTIVE',
      created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
      updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
      FOREIGN KEY (hotel_id) REFERENCES hotels(id) ON DELETE CASCADE,
      INDEX idx_hotel_id (hotel_id), INDEX idx_status (status)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
  `);

  await knex.raw(`
    CREATE TABLE IF NOT EXISTS room_amenities (
      id INT AUTO_INCREMENT PRIMARY KEY,
      room_type_id VARCHAR(36) NOT NULL, amenity_name VARCHAR(100) NOT NULL,
      is_available BOOLEAN DEFAULT TRUE,
      FOREIGN KEY (room_type_id) REFERENCES room_types(id) ON DELETE CASCADE,
      INDEX idx_room_type_id (room_type_id),
      UNIQUE KEY unique_room_amenity (room_type_id, amenity_name)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
  `);

  await knex.raw(`
    CREATE TABLE IF NOT EXISTS room_images (
      id INT AUTO_INCREMENT PRIMARY KEY,
      room_type_id VARCHAR(36) NOT NULL, image_url VARCHAR(500) NOT NULL,
      display_order INT DEFAULT 0,
      created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
      FOREIGN KEY (room_type_id) REFERENCES room_types(id) ON DELETE CASCADE,
      INDEX idx_room_type_id (room_type_id)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
  `);

  await knex.raw(`
    CREATE TABLE IF NOT EXISTS bookings (
      id VARCHAR(36) PRIMARY KEY,
      company_id VARCHAR(36) NOT NULL, customer_id VARCHAR(36) NOT NULL,
      service_type ENUM('HOTEL','TAXI','EXPERIENCE','CAR','FOOD') NOT NULL,
      booking_source ENUM('DIRECT','STAFF_CREATED','AGENT','BROKER','API','ADMIN') DEFAULT 'DIRECT',
      agent_id VARCHAR(36) NULL, staff_created_by VARCHAR(36) NULL,
      status ENUM('PENDING','CONFIRMED','COMPLETED','CANCELLED','REFUNDED') DEFAULT 'PENDING',
      payment_status ENUM('PENDING','PAID','PARTIAL_REFUND','FULLY_REFUNDED','FAILED') DEFAULT 'PENDING',
      currency VARCHAR(3) DEFAULT 'USD',
      subtotal DECIMAL(12,2) NOT NULL, tax DECIMAL(12,2) DEFAULT 0, total DECIMAL(12,2) NOT NULL,
      refund_amount DECIMAL(12,2) NULL DEFAULT 0,
      refund_reason VARCHAR(255) NULL, refunded_at TIMESTAMP NULL,
      payment_link_id VARCHAR(255) NULL, payment_link_url TEXT NULL,
      payment_link_expires_at TIMESTAMP NULL, hold_expires_at TIMESTAMP NULL,
      broker_notes TEXT NULL, guest_details JSON NULL, metadata JSON,
      created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
      updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
      FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE,
      FOREIGN KEY (customer_id) REFERENCES users(id) ON DELETE CASCADE,
      INDEX idx_company_id (company_id), INDEX idx_customer_id (customer_id),
      INDEX idx_status (status), INDEX idx_payment_status (payment_status),
      INDEX idx_booking_source (booking_source), INDEX idx_agent_id (agent_id),
      INDEX idx_service_type (service_type), INDEX idx_created_at (created_at),
      INDEX idx_hold_expires (hold_expires_at)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
  `);

  await knex.raw(`
    CREATE TABLE IF NOT EXISTS reviews (
      id VARCHAR(36) PRIMARY KEY,
      booking_id VARCHAR(36) NOT NULL, company_id VARCHAR(36) NOT NULL,
      customer_id VARCHAR(36) NOT NULL,
      service_type ENUM('HOTEL','TAXI','EXPERIENCE','CAR','FOOD') NOT NULL,
      rating INT NOT NULL, title VARCHAR(255) NOT NULL, comment TEXT NOT NULL,
      criteria JSON, status ENUM('PENDING','APPROVED','REJECTED','FLAGGED') DEFAULT 'PENDING',
      is_verified BOOLEAN DEFAULT FALSE, helpful_count INT DEFAULT 0,
      created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
      updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
      FOREIGN KEY (booking_id) REFERENCES bookings(id) ON DELETE CASCADE,
      FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE,
      FOREIGN KEY (customer_id) REFERENCES users(id) ON DELETE CASCADE,
      INDEX idx_company_id (company_id), INDEX idx_customer_id (customer_id),
      INDEX idx_status (status), INDEX idx_rating (rating)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
  `);

  await knex.raw(`
    CREATE TABLE IF NOT EXISTS roles (
      id INT AUTO_INCREMENT PRIMARY KEY,
      name VARCHAR(50) NOT NULL UNIQUE, description TEXT,
      is_system BOOLEAN DEFAULT FALSE,
      created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
      updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
      INDEX idx_name (name)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
  `);

  await knex.raw(`
    CREATE TABLE IF NOT EXISTS permissions (
      id INT AUTO_INCREMENT PRIMARY KEY,
      name VARCHAR(100) NOT NULL UNIQUE, description TEXT,
      resource VARCHAR(50) NOT NULL, action VARCHAR(50) NOT NULL,
      created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
      INDEX idx_name (name), INDEX idx_resource_action (resource, action)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
  `);

  await knex.raw(`
    CREATE TABLE IF NOT EXISTS role_permissions (
      id INT AUTO_INCREMENT PRIMARY KEY,
      role_id INT NOT NULL, permission_id INT NOT NULL,
      created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
      FOREIGN KEY (role_id) REFERENCES roles(id) ON DELETE CASCADE,
      FOREIGN KEY (permission_id) REFERENCES permissions(id) ON DELETE CASCADE,
      UNIQUE KEY unique_role_permission (role_id, permission_id),
      INDEX idx_role_id (role_id), INDEX idx_permission_id (permission_id)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
  `);

  await knex.raw(`
    CREATE TABLE IF NOT EXISTS user_permissions (
      id INT AUTO_INCREMENT PRIMARY KEY,
      user_id VARCHAR(36) NOT NULL, permission_id INT NOT NULL,
      created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
      FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
      FOREIGN KEY (permission_id) REFERENCES permissions(id) ON DELETE CASCADE,
      UNIQUE KEY unique_user_permission (user_id, permission_id),
      INDEX idx_user_id (user_id), INDEX idx_permission_id (permission_id)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
  `);

  await knex.raw(`
    CREATE TABLE IF NOT EXISTS bank_details (
      id INT AUTO_INCREMENT PRIMARY KEY,
      agent_id VARCHAR(36) NOT NULL UNIQUE,
      account_holder VARCHAR(255) NOT NULL, account_number VARCHAR(50) NOT NULL,
      routing_number VARCHAR(50) NOT NULL,
      created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
      updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
      FOREIGN KEY (agent_id) REFERENCES agents(id) ON DELETE CASCADE
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
  `);

  await knex.raw(`
    CREATE TABLE IF NOT EXISTS agent_documents (
      id INT AUTO_INCREMENT PRIMARY KEY,
      agent_id VARCHAR(36) NOT NULL,
      document_type ENUM('BUSINESS_LICENSE','TAX_ID','IDENTITY_PROOF') NOT NULL,
      document_url VARCHAR(500) NOT NULL, is_verified BOOLEAN DEFAULT FALSE,
      created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
      updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
      FOREIGN KEY (agent_id) REFERENCES agents(id) ON DELETE CASCADE,
      INDEX idx_agent_id (agent_id)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
  `);

  await knex.raw(`
    CREATE TABLE IF NOT EXISTS checkouts (
      id VARCHAR(36) PRIMARY KEY,
      customerId VARCHAR(36) NOT NULL, bookingItems LONGTEXT NOT NULL,
      subtotal DECIMAL(12,2) NOT NULL, totalTax DECIMAL(12,2) NOT NULL,
      discountAmount DECIMAL(12,2) DEFAULT 0, discountCode VARCHAR(50),
      finalTotal DECIMAL(12,2) NOT NULL, currency VARCHAR(3) DEFAULT 'GBP',
      status ENUM('ACTIVE','COMPLETED','ABANDONED','EXPIRED') DEFAULT 'ACTIVE',
      expiresAt TIMESTAMP NOT NULL,
      createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
      updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
      FOREIGN KEY (customerId) REFERENCES users(id) ON DELETE CASCADE,
      INDEX idx_customerId (customerId), INDEX idx_status (status),
      INDEX idx_expiresAt (expiresAt), INDEX idx_createdAt (createdAt)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
  `);

  await knex.raw(`
    CREATE TABLE IF NOT EXISTS checkout_sessions (
      id VARCHAR(36) PRIMARY KEY,
      sessionId VARCHAR(36) NOT NULL, customerId VARCHAR(36),
      email VARCHAR(255), bookingItems LONGTEXT NOT NULL,
      subtotal DECIMAL(12,2) NOT NULL, totalTax DECIMAL(12,2) NOT NULL,
      discountAmount DECIMAL(12,2) DEFAULT 0, discountCode VARCHAR(50),
      finalTotal DECIMAL(12,2) NOT NULL, currency VARCHAR(3) DEFAULT 'GBP',
      status ENUM('ACTIVE','COMPLETED','ABANDONED','EXPIRED') DEFAULT 'ACTIVE',
      isGuest BOOLEAN DEFAULT FALSE, expiresAt TIMESTAMP NOT NULL,
      createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
      updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
      FOREIGN KEY (customerId) REFERENCES users(id) ON DELETE CASCADE,
      INDEX idx_sessionId (sessionId), INDEX idx_customerId (customerId),
      INDEX idx_email (email), INDEX idx_status (status),
      INDEX idx_isGuest (isGuest), INDEX idx_expiresAt (expiresAt)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
  `);

  // ── Migration 001: hotel filters ───────────────────────────────────────────

  await knex.raw(`
    CREATE TABLE IF NOT EXISTS hotel_facilities (
      id INT AUTO_INCREMENT PRIMARY KEY,
      hotel_id VARCHAR(36) NOT NULL, facility_name VARCHAR(100) NOT NULL,
      FOREIGN KEY (hotel_id) REFERENCES hotels(id) ON DELETE CASCADE,
      INDEX idx_hotel_id (hotel_id),
      UNIQUE KEY unique_hotel_facility (hotel_id, facility_name)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
  `);

  await knex.raw(`
    CREATE TABLE IF NOT EXISTS room_facilities (
      id INT AUTO_INCREMENT PRIMARY KEY,
      room_type_id VARCHAR(36) NOT NULL, facility_name VARCHAR(100) NOT NULL,
      FOREIGN KEY (room_type_id) REFERENCES room_types(id) ON DELETE CASCADE,
      INDEX idx_room_type_id (room_type_id),
      UNIQUE KEY unique_room_facility (room_type_id, facility_name)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
  `);

  await knex.raw(`
    CREATE TABLE IF NOT EXISTS hotel_landmarks (
      id INT AUTO_INCREMENT PRIMARY KEY,
      hotel_id VARCHAR(36) NOT NULL, landmark_name VARCHAR(255) NOT NULL,
      distance_km DECIMAL(5,2) NOT NULL, landmark_type VARCHAR(50),
      FOREIGN KEY (hotel_id) REFERENCES hotels(id) ON DELETE CASCADE,
      INDEX idx_hotel_id (hotel_id), INDEX idx_landmark_type (landmark_type)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
  `);

  await knex.raw(`
    CREATE TABLE IF NOT EXISTS hotel_surroundings (
      id INT AUTO_INCREMENT PRIMARY KEY,
      hotel_id VARCHAR(36) NOT NULL UNIQUE,
      restaurants_nearby BOOLEAN DEFAULT FALSE, cafes_nearby BOOLEAN DEFAULT FALSE,
      top_attractions BOOLEAN DEFAULT FALSE, natural_beauty BOOLEAN DEFAULT FALSE,
      public_transport BOOLEAN DEFAULT FALSE, closest_airport_km DECIMAL(5,2),
      created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
      updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
      FOREIGN KEY (hotel_id) REFERENCES hotels(id) ON DELETE CASCADE,
      INDEX idx_hotel_id (hotel_id)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
  `);

  // ── Migrations 002–007: admin system ──────────────────────────────────────

  await knex.raw(`
    CREATE TABLE IF NOT EXISTS admin_users (
      id INT AUTO_INCREMENT PRIMARY KEY,
      email VARCHAR(255) NOT NULL UNIQUE, password_hash VARCHAR(255) NOT NULL,
      full_name VARCHAR(255) NOT NULL,
      role VARCHAR(50) NOT NULL DEFAULT 'SUPER_ADMIN',
      status VARCHAR(50) NOT NULL DEFAULT 'ACTIVE',
      mfa_enabled BOOLEAN NOT NULL DEFAULT FALSE, mfa_secret VARCHAR(255),
      created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
      updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
      last_login_at TIMESTAMP NULL, created_by_id INT,
      FOREIGN KEY (created_by_id) REFERENCES admin_users(id) ON DELETE SET NULL,
      INDEX idx_email (email), INDEX idx_status (status),
      INDEX idx_created_at (created_at), INDEX idx_created_by_id (created_by_id)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
  `);

  await knex.raw(`
    CREATE TABLE IF NOT EXISTS admin_sessions (
      id INT AUTO_INCREMENT PRIMARY KEY,
      admin_user_id INT NOT NULL, token_hash VARCHAR(255) NOT NULL UNIQUE,
      ip_address VARCHAR(45), user_agent TEXT,
      expires_at TIMESTAMP NOT NULL,
      created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
      FOREIGN KEY (admin_user_id) REFERENCES admin_users(id) ON DELETE CASCADE,
      INDEX idx_admin_user_id (admin_user_id), INDEX idx_expires_at (expires_at),
      INDEX idx_token_hash (token_hash)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
  `);

  await knex.raw(`
    CREATE TABLE IF NOT EXISTS audit_logs (
      id INT AUTO_INCREMENT PRIMARY KEY,
      admin_user_id INT NOT NULL,
      action_type VARCHAR(50) NOT NULL, entity_type VARCHAR(50) NOT NULL,
      entity_id INT, old_values JSON, new_values JSON, reason TEXT,
      ip_address VARCHAR(45), user_agent TEXT,
      created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
      FOREIGN KEY (admin_user_id) REFERENCES admin_users(id) ON DELETE RESTRICT,
      INDEX idx_admin_user_id (admin_user_id), INDEX idx_created_at (created_at),
      INDEX idx_entity_type (entity_type), INDEX idx_action_type (action_type),
      INDEX idx_entity_id (entity_id)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
  `);

  await knex.raw(`
    CREATE TABLE IF NOT EXISTS admin_alerts (
      id INT AUTO_INCREMENT PRIMARY KEY,
      alert_type VARCHAR(100) NOT NULL UNIQUE, severity VARCHAR(20) NOT NULL,
      title VARCHAR(255) NOT NULL, description TEXT,
      threshold_value DECIMAL(10,2),
      is_enabled BOOLEAN NOT NULL DEFAULT TRUE,
      created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
      updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
      INDEX idx_alert_type (alert_type), INDEX idx_severity (severity),
      INDEX idx_is_enabled (is_enabled)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
  `);

  await knex.raw(`
    CREATE TABLE IF NOT EXISTS alert_history (
      id INT AUTO_INCREMENT PRIMARY KEY,
      alert_id INT NOT NULL, triggered_at TIMESTAMP NOT NULL,
      current_value DECIMAL(10,2), acknowledged_by_id INT,
      acknowledged_at TIMESTAMP NULL,
      created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
      FOREIGN KEY (alert_id) REFERENCES admin_alerts(id) ON DELETE CASCADE,
      FOREIGN KEY (acknowledged_by_id) REFERENCES admin_users(id) ON DELETE SET NULL,
      INDEX idx_alert_id (alert_id), INDEX idx_triggered_at (triggered_at)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
  `);

  await knex.raw(`
    CREATE TABLE IF NOT EXISTS admin_preferences (
      id INT AUTO_INCREMENT PRIMARY KEY,
      admin_user_id INT NOT NULL UNIQUE,
      theme VARCHAR(20) NOT NULL DEFAULT 'light',
      items_per_page INT NOT NULL DEFAULT 25,
      notifications_enabled BOOLEAN NOT NULL DEFAULT TRUE,
      email_alerts BOOLEAN NOT NULL DEFAULT TRUE,
      created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
      updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
      FOREIGN KEY (admin_user_id) REFERENCES admin_users(id) ON DELETE CASCADE,
      INDEX idx_admin_user_id (admin_user_id)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
  `);

  // ── Migration 008: Haram gates ─────────────────────────────────────────────

  await knex.raw(`
    CREATE TABLE IF NOT EXISTS haram_gates (
      id VARCHAR(36) PRIMARY KEY,
      gate_number INT NOT NULL UNIQUE,
      name_english VARCHAR(255) NOT NULL, name_arabic VARCHAR(255),
      latitude DECIMAL(10,8), longitude DECIMAL(11,8),
      has_direct_kaaba_access BOOLEAN DEFAULT FALSE,
      floor_level INT, description TEXT,
      created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
      updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
      INDEX idx_gate_number (gate_number)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
  `);

  await knex.raw(`
    CREATE TABLE IF NOT EXISTS hotel_gate_distances (
      id VARCHAR(36) PRIMARY KEY,
      hotel_id VARCHAR(36) NOT NULL, gate_id VARCHAR(36) NOT NULL,
      distance_meters INT, walking_time_minutes INT,
      is_recommended BOOLEAN DEFAULT FALSE,
      created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
      FOREIGN KEY (hotel_id) REFERENCES hotels(id) ON DELETE CASCADE,
      FOREIGN KEY (gate_id) REFERENCES haram_gates(id),
      UNIQUE KEY unique_hotel_gate (hotel_id, gate_id),
      INDEX idx_hotel_id (hotel_id), INDEX idx_gate_id (gate_id),
      INDEX idx_distance_meters (distance_meters)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
  `);

  // ── Migration 010: Credits & payments ─────────────────────────────────────

  await knex.raw(`
    CREATE TABLE IF NOT EXISTS transactions (
      id VARCHAR(36) PRIMARY KEY,
      booking_id VARCHAR(36), user_id VARCHAR(36) NOT NULL,
      type VARCHAR(50) NOT NULL, amount DECIMAL(12,2) NOT NULL,
      currency VARCHAR(3) DEFAULT 'GBP', status VARCHAR(50) DEFAULT 'PENDING',
      provider VARCHAR(50), provider_reference VARCHAR(255),
      metadata JSON, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
      updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
      INDEX idx_booking_id (booking_id), INDEX idx_user_id (user_id),
      INDEX idx_status (status)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
  `);

  await knex.raw(`
    CREATE TABLE IF NOT EXISTS payments (
      id VARCHAR(36) PRIMARY KEY,
      booking_id VARCHAR(36), user_id VARCHAR(36) NOT NULL,
      amount DECIMAL(12,2) NOT NULL, currency VARCHAR(3) DEFAULT 'GBP',
      status VARCHAR(50) DEFAULT 'PENDING', method VARCHAR(50),
      provider VARCHAR(50), provider_reference VARCHAR(255),
      metadata JSON, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
      updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
      INDEX idx_booking_id (booking_id), INDEX idx_user_id (user_id),
      INDEX idx_status (status)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
  `);

  await knex.raw(`
    CREATE TABLE IF NOT EXISTS exchange_rates (
      id VARCHAR(36) PRIMARY KEY,
      from_currency VARCHAR(3) NOT NULL, to_currency VARCHAR(3) NOT NULL,
      rate DECIMAL(10,6) NOT NULL, source VARCHAR(50) DEFAULT 'manual',
      fetched_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
      expires_at TIMESTAMP NULL,
      UNIQUE KEY unique_currency_pair (from_currency, to_currency),
      INDEX idx_currencies (from_currency, to_currency)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
  `);

  await knex.raw(`
    CREATE TABLE IF NOT EXISTS user_credits (
      id VARCHAR(36) PRIMARY KEY,
      user_id VARCHAR(36) NOT NULL UNIQUE,
      balance BIGINT NOT NULL DEFAULT 0,
      currency VARCHAR(3) DEFAULT 'GBP',
      created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
      updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
      FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
      INDEX idx_user_id (user_id)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
  `);

  await knex.raw(`
    CREATE TABLE IF NOT EXISTS credit_transactions (
      id VARCHAR(36) PRIMARY KEY,
      user_id VARCHAR(36) NOT NULL, booking_id VARCHAR(36),
      type ENUM('EARN','SPEND','REFUND','ADJUSTMENT','BONUS') NOT NULL,
      amount BIGINT NOT NULL, balance_after BIGINT NOT NULL,
      currency_original VARCHAR(3), amount_original DECIMAL(12,2),
      exchange_rate DECIMAL(10,6), description VARCHAR(255), metadata JSON,
      created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
      FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
      FOREIGN KEY (booking_id) REFERENCES bookings(id) ON DELETE SET NULL,
      INDEX idx_user_id (user_id), INDEX idx_booking_id (booking_id),
      INDEX idx_type (type), INDEX idx_created_at (created_at)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
  `);

  await knex.raw(`
    CREATE TABLE IF NOT EXISTS email_audit_log (
      id VARCHAR(36) PRIMARY KEY,
      recipient_email VARCHAR(255) NOT NULL, subject VARCHAR(255),
      email_type VARCHAR(50),
      status ENUM('PENDING','SENT','FAILED','BOUNCED') DEFAULT 'PENDING',
      error_message TEXT, sent_at TIMESTAMP NULL,
      created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
      updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
      INDEX idx_recipient_email (recipient_email), INDEX idx_status (status),
      INDEX idx_email_type (email_type), INDEX idx_created_at (created_at)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
  `);

  // ── Migration 011: Hajj/Umrah features ────────────────────────────────────

  await knex.raw(`
    CREATE TABLE IF NOT EXISTS hotel_best_for_tags (
      id INT AUTO_INCREMENT PRIMARY KEY,
      hotel_id VARCHAR(36) NOT NULL, tag VARCHAR(50) NOT NULL,
      created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
      FOREIGN KEY (hotel_id) REFERENCES hotels(id) ON DELETE CASCADE,
      INDEX idx_hotel_id (hotel_id), INDEX idx_tag (tag),
      UNIQUE KEY unique_hotel_tag (hotel_id, tag)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
  `);

  // ── Migration 013: Guest details ───────────────────────────────────────────

  await knex.raw(`
    CREATE TABLE IF NOT EXISTS guests (
      id VARCHAR(36) PRIMARY KEY,
      booking_id VARCHAR(36) NOT NULL,
      first_name VARCHAR(100) NOT NULL, last_name VARCHAR(100) NOT NULL,
      email VARCHAR(255) NOT NULL, phone VARCHAR(20), nationality VARCHAR(100),
      is_lead_passenger BOOLEAN DEFAULT FALSE,
      passport_number VARCHAR(50), date_of_birth DATE,
      created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
      updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
      FOREIGN KEY (booking_id) REFERENCES bookings(id) ON DELETE CASCADE,
      INDEX idx_booking_id (booking_id), INDEX idx_email (email)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
  `);

  // ── Migration 014: Messaging tables ───────────────────────────────────────

  await knex.raw(`
    CREATE TABLE IF NOT EXISTS conversations (
      id VARCHAR(36) PRIMARY KEY,
      hotel_id VARCHAR(36) NOT NULL, booking_id VARCHAR(36),
      subject VARCHAR(255) NOT NULL, description TEXT,
      status ENUM('ACTIVE','ARCHIVED','CLOSED') DEFAULT 'ACTIVE',
      created_by_id VARCHAR(36) NOT NULL,
      created_by_role ENUM('GUEST','BROKER','HOTEL_STAFF','MANAGER','ADMIN') NOT NULL,
      created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
      updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
      FOREIGN KEY (hotel_id) REFERENCES hotels(id) ON DELETE CASCADE,
      INDEX idx_hotel_id (hotel_id), INDEX idx_booking_id (booking_id),
      INDEX idx_status (status), INDEX idx_created_at (created_at)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
  `);

  await knex.raw(`
    CREATE TABLE IF NOT EXISTS conversation_participants (
      id VARCHAR(36) PRIMARY KEY,
      conversation_id VARCHAR(36) NOT NULL, user_id VARCHAR(36) NOT NULL,
      user_role ENUM('GUEST','BROKER','HOTEL_STAFF','MANAGER','ADMIN') NOT NULL,
      hotel_id VARCHAR(36),
      is_read BOOLEAN DEFAULT FALSE, last_read_at TIMESTAMP NULL,
      joined_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, left_at TIMESTAMP NULL,
      FOREIGN KEY (conversation_id) REFERENCES conversations(id) ON DELETE CASCADE,
      UNIQUE KEY unique_participant (conversation_id, user_id),
      INDEX idx_conversation_id (conversation_id), INDEX idx_user_id (user_id)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
  `);

  await knex.raw(`
    CREATE TABLE IF NOT EXISTS messages (
      id VARCHAR(36) PRIMARY KEY,
      conversation_id VARCHAR(36) NOT NULL, sender_id VARCHAR(36) NOT NULL,
      sender_role ENUM('GUEST','BROKER','HOTEL_STAFF','MANAGER','ADMIN') NOT NULL,
      content TEXT NOT NULL, content_sanitized TEXT,
      message_type ENUM('TEXT','SYSTEM','UPGRADE_OFFER') DEFAULT 'TEXT',
      metadata JSON, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
      updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
      deleted_at TIMESTAMP NULL,
      FOREIGN KEY (conversation_id) REFERENCES conversations(id) ON DELETE CASCADE,
      INDEX idx_conversation_id (conversation_id), INDEX idx_sender_id (sender_id),
      INDEX idx_created_at (created_at)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
  `);

  await knex.raw(`
    CREATE TABLE IF NOT EXISTS message_read_receipts (
      id VARCHAR(36) PRIMARY KEY,
      message_id VARCHAR(36) NOT NULL, user_id VARCHAR(36) NOT NULL,
      read_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
      FOREIGN KEY (message_id) REFERENCES messages(id) ON DELETE CASCADE,
      UNIQUE KEY unique_receipt (message_id, user_id),
      INDEX idx_message_id (message_id), INDEX idx_user_id (user_id)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
  `);

  await knex.raw(`
    CREATE TABLE IF NOT EXISTS conversation_assignments (
      id VARCHAR(36) PRIMARY KEY,
      conversation_id VARCHAR(36) NOT NULL,
      assigned_to_id VARCHAR(36) NOT NULL, assigned_by_id VARCHAR(36) NOT NULL,
      assigned_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, unassigned_at TIMESTAMP NULL,
      FOREIGN KEY (conversation_id) REFERENCES conversations(id) ON DELETE CASCADE,
      INDEX idx_conversation_id (conversation_id), INDEX idx_assigned_to_id (assigned_to_id)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
  `);

  await knex.raw(`
    CREATE TABLE IF NOT EXISTS message_audit_log (
      id VARCHAR(36) PRIMARY KEY,
      conversation_id VARCHAR(36), message_id VARCHAR(36),
      user_id VARCHAR(36) NOT NULL, action VARCHAR(50) NOT NULL,
      details JSON, ip_address VARCHAR(45),
      created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
      INDEX idx_conversation_id (conversation_id), INDEX idx_message_id (message_id),
      INDEX idx_user_id (user_id), INDEX idx_created_at (created_at)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
  `);

  // ── Migration 016: Scoring system ─────────────────────────────────────────

  await knex.raw(`
    CREATE TABLE IF NOT EXISTS scoring_weights (
      id INT AUTO_INCREMENT PRIMARY KEY,
      location_weight DECIMAL(5,2) NOT NULL DEFAULT 35.00,
      pilgrim_suitability_weight DECIMAL(5,2) NOT NULL DEFAULT 25.00,
      hotel_quality_weight DECIMAL(5,2) NOT NULL DEFAULT 20.00,
      experience_friction_weight DECIMAL(5,2) NOT NULL DEFAULT 10.00,
      user_reviews_weight DECIMAL(5,2) NOT NULL DEFAULT 10.00,
      updated_by VARCHAR(36) NULL,
      updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
      created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
  `);

  // ── Migration 019: Gate assignments & payment links ───────────────────────

  await knex.raw(`
    CREATE TABLE IF NOT EXISTS hotel_gate_assignments (
      id VARCHAR(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci PRIMARY KEY,
      hotel_id VARCHAR(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL UNIQUE,
      closest_gate_id VARCHAR(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL,
      kaaba_gate_id   VARCHAR(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL,
      created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
      updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
      FOREIGN KEY (hotel_id) REFERENCES hotels(id) ON DELETE CASCADE,
      FOREIGN KEY (closest_gate_id) REFERENCES haram_gates(id),
      FOREIGN KEY (kaaba_gate_id)   REFERENCES haram_gates(id),
      INDEX idx_hotel_id (hotel_id)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4
  `);

  await knex.raw(`
    CREATE TABLE IF NOT EXISTS payment_links (
      id VARCHAR(36) PRIMARY KEY,
      booking_id VARCHAR(36) NOT NULL UNIQUE, token VARCHAR(255) NOT NULL UNIQUE,
      guest_email VARCHAR(255) NOT NULL,
      amount DECIMAL(12,2) NOT NULL, currency VARCHAR(3) NOT NULL,
      status ENUM('SENT','CLICKED','EXPIRED','COMPLETED') DEFAULT 'SENT',
      created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
      expires_at TIMESTAMP NOT NULL,
      clicked_at TIMESTAMP NULL, completed_at TIMESTAMP NULL,
      stripe_session_id VARCHAR(255),
      FOREIGN KEY (booking_id) REFERENCES bookings(id) ON DELETE CASCADE,
      INDEX idx_booking_id (booking_id), INDEX idx_token (token),
      INDEX idx_status (status), INDEX idx_expires_at (expires_at)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
  `);

  await knex.raw(`
    CREATE TABLE IF NOT EXISTS hotel_filters (
      id INT AUTO_INCREMENT PRIMARY KEY,
      filter_name VARCHAR(100) NOT NULL UNIQUE,
      filter_description TEXT, filter_type VARCHAR(50),
      created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
  `);

  await knex.raw(`
    CREATE TABLE IF NOT EXISTS nearby_attractions (
      id VARCHAR(36) PRIMARY KEY,
      name VARCHAR(255) NOT NULL, attraction_type VARCHAR(100),
      latitude DECIMAL(10,8), longitude DECIMAL(11,8),
      description TEXT,
      created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
      updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
  `);

  await knex.raw(`
    CREATE TABLE IF NOT EXISTS hotel_attraction_distances (
      id VARCHAR(36) PRIMARY KEY,
      hotel_id VARCHAR(36) NOT NULL, attraction_id VARCHAR(36) NOT NULL,
      distance_meters INT, walking_time_minutes INT,
      created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
      FOREIGN KEY (hotel_id) REFERENCES hotels(id) ON DELETE CASCADE,
      UNIQUE KEY unique_hotel_attraction (hotel_id, attraction_id),
      INDEX idx_hotel_id (hotel_id)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
  `);

  // ── Add missing columns to existing tables (idempotent via hasColumn) ──────

  // hotels — Hajj/Umrah features (011)
  await addCol(knex, 'hotels', 'walking_time_to_haram',    t => t.integer('walking_time_to_haram').nullable());
  await addCol(knex, 'hotels', 'view_type',                t => t.enu('view_type', ['kaaba','partial_haram','city','none']).defaultTo('none'));
  await addCol(knex, 'hotels', 'is_elderly_friendly',      t => t.boolean('is_elderly_friendly').defaultTo(false));
  await addCol(knex, 'hotels', 'has_family_rooms',         t => t.boolean('has_family_rooms').defaultTo(false));
  await addCol(knex, 'hotels', 'manasik_score',            t => t.decimal('manasik_score', 3, 1).nullable());
  await addCol(knex, 'hotels', 'distance_to_haram_meters', t => t.integer('distance_to_haram_meters').nullable());
  await addCol(knex, 'hotels', 'nearest_gate_id',          t => t.string('nearest_gate_id', 36).nullable());
  // hotels — provider (012)
  await addCol(knex, 'hotels', 'provider_name',      t => t.string('provider_name', 255).nullable());
  await addCol(knex, 'hotels', 'provider_reference', t => t.string('provider_reference', 100).nullable());
  await addCol(knex, 'hotels', 'provider_phone',     t => t.string('provider_phone', 20).nullable());
  // hotels — scoring/rules/policies/gates (016–019)
  await addCol(knex, 'hotels', 'scoring_data',   t => t.json('scoring_data').nullable());
  await addCol(knex, 'hotels', 'hotel_rules',    t => t.text('hotel_rules').nullable());
  await addCol(knex, 'hotels', 'gates_assigned', t => t.boolean('gates_assigned').defaultTo(false));

  // bookings — all incremental additions (010, 011, 013, 015)
  await addCol(knex, 'bookings', 'staff_created_by',        t => t.string('staff_created_by', 36).nullable());
  await addCol(knex, 'bookings', 'refund_amount',           t => t.decimal('refund_amount', 12, 2).nullable().defaultTo(0));
  await addCol(knex, 'bookings', 'refund_reason',           t => t.string('refund_reason', 255).nullable());
  await addCol(knex, 'bookings', 'refunded_at',             t => t.timestamp('refunded_at').nullable());
  await addCol(knex, 'bookings', 'payment_link_url',        t => t.text('payment_link_url').nullable());
  await addCol(knex, 'bookings', 'payment_link_expires_at', t => t.timestamp('payment_link_expires_at').nullable());
  await addCol(knex, 'bookings', 'hold_expires_at',         t => t.timestamp('hold_expires_at').nullable());
  await addCol(knex, 'bookings', 'broker_notes',            t => t.text('broker_notes').nullable());

  // room_types — family rooms (011)
  await addCol(knex, 'room_types', 'is_family_room',       t => t.boolean('is_family_room').defaultTo(false));
  await addCol(knex, 'room_types', 'max_adults',           t => t.integer('max_adults').defaultTo(2));
  await addCol(knex, 'room_types', 'max_children',         t => t.integer('max_children').defaultTo(0));
  await addCol(knex, 'room_types', 'has_connecting_rooms', t => t.boolean('has_connecting_rooms').defaultTo(false));

  // ── Seed default data ──────────────────────────────────────────────────────

  await knex.raw(`
    INSERT IGNORE INTO admin_alerts (alert_type, severity, title, description, threshold_value, is_enabled) VALUES
    ('HIGH_REFUND_RATE',          'WARNING',  'High Refund Rate',          'Alert when refund rate exceeds threshold', 10.00, TRUE),
    ('PAYMENT_FAILURES',          'CRITICAL', 'Payment Failures',          'Alert when payment failure rate is high',   5.00, TRUE),
    ('SUSPICIOUS_ACTIVITY',       'CRITICAL', 'Suspicious Activity',       'Alert when suspicious activity detected',   NULL, TRUE),
    ('LOW_PLATFORM_UPTIME',       'CRITICAL', 'Low Platform Uptime',       'Alert when uptime drops below threshold',  99.00, TRUE),
    ('HIGH_BOOKING_CANCELLATION', 'WARNING',  'High Booking Cancellation', 'Alert when cancellation rate is high',     15.00, TRUE),
    ('NEGATIVE_REVIEWS',          'WARNING',  'Negative Reviews',          'Alert when average rating drops below threshold', 3.50, TRUE)
  `);

  await knex.raw(`
    INSERT INTO scoring_weights (location_weight, pilgrim_suitability_weight, hotel_quality_weight, experience_friction_weight, user_reviews_weight)
    SELECT 35.00, 25.00, 20.00, 10.00, 10.00
    WHERE NOT EXISTS (SELECT 1 FROM scoring_weights LIMIT 1)
  `);

  await knex.raw('SET FOREIGN_KEY_CHECKS = 1');
}

// ─── Down ─────────────────────────────────────────────────────────────────────

export async function down(_knex: Knex): Promise<void> {
  // The baseline is never rolled back — it represents the founding schema.
  // Rolling back would drop all tables and all data.
}
